john jay dining hall 
No privacy notice found or it didn't appear in time
Traceback (most recent call last):
  File "C:\Users\carol\lion-dine\lion-dine\lion-dine\scrape.py", line 218, in <module>
    scrape_and_save()
  File "C:\Users\carol\lion-dine\lion-dine\lion-dine\scrape.py", line 201, in scrape_and_save
    data = scrape_all()
           ^^^^^^^^^^^^
  File "C:\Users\carol\lion-dine\lion-dine\lion-dine\scrape.py", line 186, in scrape_all
    hall_data = scrape_columbia(hall)
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\carol\lion-dine\lion-dine\lion-dine\scrape.py", line 102, in scrape_columbia
    with managed_webdriver() as driver:
  File "C:\Users\carol\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Users\carol\lion-dine\lion-dine\lion-dine\scrape.py", line 87, in managed_webdriver
    driver = webdriver.Chrome(service=service, options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\carol\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\carol\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 61, in __init__
    super().__init__(command_executor=executor, options=options)
  File "C:\Users\carol\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 209, in __init__
    self.start_session(capabilities)
  File "C:\Users\carol\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 293, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\carol\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "C:\Users\carol\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from disconnected: unable to connect to renderer
Stacktrace:
	GetHandleVerifier [0x002FEBD3+24307]
	(No symbol) [0x00288D74]
	(No symbol) [0x0016C323]
	(No symbol) [0x0019F110]
	(No symbol) [0x0019A37F]
	(No symbol) [0x001956B9]
	(No symbol) [0x001D93B5]
	(No symbol) [0x001D8B9A]
	(No symbol) [0x001CFC26]
	(No symbol) [0x001A219C]
	(No symbol) [0x001A311D]
	GetHandleVerifier [0x005A8D93+2818227]
	GetHandleVerifier [0x0060542E+3196750]
	GetHandleVerifier [0x005FD9D2+3165426]
	GetHandleVerifier [0x0039DA70+675216]
	(No symbol) [0x00291B3D]
	(No symbol) [0x0028EA18]
	(No symbol) [0x0028EBB5]
	(No symbol) [0x00281640]
	BaseThreadInitThunk [0x76AC7BA9+25]
	RtlInitializeExceptionChain [0x777AC0CB+107]
	RtlClearBits [0x777AC04F+191]
	(No symbol) [0x00000000]

